name: Publish Docker image
on:
  push: {branches: master}
jobs:
  test_main_docker:
    name: Test the main docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check environment
        run: |
          ls
          pwd
      - name: Build Dockerfile
        run: docker build -t mymecab .
      - name: Run Dockerfile with mecab
        run: docker run -it --rm mymecab /bin/bash -c 'cat test.txt | mecab'
      - name: Run Dockerfile with mecab
        run: docker run -it --rm mymecab /bin/bash -c 'cat test.txt | mecab -d /usr/lib/mecab/dic/mecab-ipadic-neologd/'



